version = 1

test_patterns = ["test/**"]

exclude_patterns = ["external/**"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "test-coverage"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "ruff"

[[transformers]]
name = "black"